Window
    .title: 'New Uploader 1.0.0'
    Frame
        .grid: {'row': 0, 'column': 0, 'sticky': 'nw', 'padx': 10}
        TextSpan
            id: 'Labels'
            type: Label
            mode: 'row'
            column: 0
            values: TEXT_VALUES
    Frame
        .grid: {'row': 0, 'column': 1, 'sticky': 'nw', 'pady': 10}
        Entry
            id: 'path_entry'
            width: 50
            .grid: {'row': 0, 'column': 0, 'sticky': 'nw'}
        Entry
            id: 'version_entry'
            width: 15
            .bind: ('<Key>' | $reset_entry(self))
            .grid: {'row': 1, 'column': 0, 'sticky': 'nw'}
        Combobox
            alias: 'option_combobox'
            id: 'github_combobox'
            .grid: {'row': 2, 'column': 0, 'sticky': 'nw'}
        Entry
            id: 'commit_entry'
            width: 30
            .grid: {'row': 3, 'column': 0, 'sticky': 'nw'}
        Combobox
            alias: 'option_combobox'
            id: 'pypi_combobox'
            .grid: {'row': 4, 'column': 0, 'sticky': 'nw'}
        Combobox
            alias: 'option_combobox'
            id: 'delete_combobox'
            .grid: {'row': 5, 'column': 0, 'sticky': 'nw'}
    Frame
        .grid: {'row': 0, 'column': 2, 'sticky': 'ne', 'padx': 10}
        Button
            text: 'Change'
            command: $update_path(#path_entry)
            .grid: {'row': 0, 'column': 0, 'sticky': 'ne', 'padx': (10, 0)}
        Button
            text: 'Validate'
            command: $validate_version(#version_entry)
            .grid: {'row': 1, 'column': 0, 'sticky': 'ne', 'padx': (10, 0)}
    Button
        text: 'Upload'
        command: $get_values(#path_entry | #version_entry | #commit_entry | #pypi_combobox | #github_combobox | #delete_combobox)
        .grid: {'row': 1, 'column': 0, 'columnspan': 3, 'sticky': 'ew', 'padx': 50, 'pady': 10}
        execute: $update_path(#path_entry | #version_entry | #commit_entry)