Tk
    id: 'window'
    .title: 'Rainbow'
    bg: '#181818'
    Frame
        id: 'red_frame'
        width: 500
        height: 500
        bg: 'red'
        .grid: {'row': 0, 'column': 0}
    Frame
        id: 'blue_frame'
        width: 500
        height: 500
        bg: 'blue'
        .grid: {'row': 0, 'column': 1}
    Button
        id: 'red_button'
        text: 'Change red'
        command: $change(#red_frame | 'bg' | ['#a62f34', '#19d9a7', '#37afdf'])
        .grid: {'row': 1, 'column': 0}
    Button
        id: 'blue_button'
        text: 'Change blue'
        command: $change(#blue_frame | 'bg' | ['#a62f34', '#19d9a7', '#37afdf'])
        .grid: {'row': 1, 'column': 1}