Tk
    .title: 'Simple UI'
    bg: '#181818'
    Frame
        bg: '#323232'
        .pack: {'padx': 50, 'pady': 50}
        Frame
            id: 'topleft_frame'
            bg: '#ff0000'
            width: 200
            height: 200
            .grid: {'row': 0, 'column': 0, 'padx': (50, 0), 'pady': (50, 0)}
        Frame
            id: 'topright_frame'
            bg: '#ffff00'
            width: 200
            height: 200
            .grid: {'row': 0, 'column': 1, 'padx': 50, 'pady': (50, 0)}
        Frame
            id: 'bottomleft_frame'
            bg: '#00ffff'
            width: 200
            height: 200
            .grid: {'row': 1, 'column': 0, 'padx': (50, 0), 'pady': 50}
        Frame
            id: 'bottomright_frame'
            bg: '#00ff00'
            width: 200
            height: 200
            .grid: {'row': 1, 'column': 1, 'padx': 50, 'pady': 50}
    Frame
        bg: 'gray'
        .pack: {}
        Button
            text: 'change self'
            command: $change(self | '#ff0000' | '#800000')
            .pack: {'side': 'left', 'pady': 10}
        Button
            text: 'change self.master'
            command: $change(self.master | '#ffff00' | '#808000')
            .pack: {'side': 'left'}
        Button
            text: 'change self.master.master'
            command: $change(self.master.master | '#00ffff' | '#008080')
            .pack: {'side': 'left'}
        Button
            text: 'print window color'
            command: $print_property(self.master.master | 'bg')
            .pack: {'side': 'left'}